# Generated by Django 3.1 on 2020-09-23 08:07

import datetime
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.ForeignKey(default=datetime.date, on_delete=models.SET(products.models.Product), to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.ForeignKey(default=datetime.date, on_delete=models.SET(products.models.Product), to='products.product'),
            preserve_default=False,
        ),
    ]
